### ISSUE TITLE
GRFON bug that is really weird and complex

### ISSUE THREAD

**Issue by MineRobber9000** [JoeStrout/minimicro-sysdisk#26]
Minimal reproducing case:

```
foo: bar
baz: {
    this is the bug: //right here
}
qux: aaa
```

Expected parsing (of course, a less forgiving parser would probably choose to error here):

```
{
    "foo": "bar",
    "baz": {"this is the bug": null},
    "qux": "aaa"
}
```

What we get instead:
```
{
    "foo": "bar",
    "baz": {"this is the bug": null, "qux": "aaa"}
}
```

By adding [a check for `asvalue` in my implementation](https://github.com/MineRobber9000/grfon-lua/blob/trunk/grfon/parser.lua#L119), I was able to achieve the former parsing (to an extent; if there's another key on the next line, it will be interpreted as the value of `"this is the bug"`, with that key's value becoming the value of `""` due to a different bug that has to do with colons in value strings but I am a firm believer in "garbage in, garbage out" and if you've stumbled across *that* bug your GRFON file has worse issues than slightly awkward parsing).

Here you can see the issue with the "Squawk Test 1" example GRFON file (which, due to the bug mentioned in the last parenthetical, interprets the author as having a `"www"` of `"http"`, a `""` of `null`, and then promptly wigs out):

![image](https://github.com/JoeStrout/minimicro-sysdisk/assets/12676241/dd87295a-1e9f-46a5-9025-ea9fed6f4007)

As you can see, `"context"` and the squawks are attributed to `"author"` despite obviously being in the top level collection.

**Comment by JoeStrout** [comment]
It's not that weird and complex — the parser's just getting confused when there is a `:` not followed by a value (but instead immediately followed by a closing `}`).  We'll need to make it more robust to that case.

But also, you bring to my attention that `://` was interpreted as just part of a string in the original C# implementation, but this behavior was never documented, and didn't make it into the MiniScript port.  That's probably a mistake we should rectify.  Having to escape `:` and `//` in any URL makes URLs really annoying, and the whole point of GRFON is to be _not_ annoying.

**Comment by MineRobber9000** [comment]
I've since fixed the `://` behavior in [grfon-lua](https://github.com/MineRobber9000/grfon-lua/commit/44fbff6f4209e9dabb28d1686bd1ed07bea31f6c) (albeit with a messed up commit message, since commit messages are apparently only Markdown when GitHub Feels Like It:tm:). I do agree that there should be some better way of handling a key with no provided value, but I'm not quite sure how.

**Comment by JoeStrout** [comment]
I've now got it handling that case by _not_ advancing past the `}` when we are trying to parse a value.  So your example now produces:
```
{"foo": "bar", "baz": {"this is the bug": null}, "bamf": 42}
```
