### ISSUE TITLE
MiniMicro partially works on WSL!

### ISSUE THREAD

**Issue by eddavis2** [JoeStrout/minimicro-sysdisk#7]
MiniMicro partially works on WSL!

But, it crashes if you try to mount a folder.

Probably a WSL problem.  I'm probably missing certain packages, just don't know what ones.

**Comment by JoeStrout** [comment]
Neat!  I guess?  I mean, why not just use the Linux version of Mini Micro?

**Comment by eddavis2** [comment]
Sorry, I wasn't clear.
That was using the Linux version.
It looks great, just crashes when I try to mount.
Probably I'm missing a library/so file, but not sure how to know which one.
--

On Thursday, March 2, 2023 at 05:19:20 PM EST, JoeStrout ***@***.***> wrote: 

Neat! I guess? I mean, why not just use the Linux version of Mini Micro?

**Comment by JoeStrout** [comment]
You can work around this by mounting the desired folder when you launch, using the -usr argument.  See: https://miniscript.org/wiki/Command-line_arguments

But it certainly shouldn't crash.  If you can get any details (error message, etc.), please attach them here!

**Comment by eddavis2** [comment]
Sadly, it does not give me any error message, except "Segmentation fault".  But no other details.

I tried the -usr switch, and that worked great!

Note however, that I also get "Segmentation fault" when I close the editor, by clicking on the [x].  Again, this is WSL, so probably not anything to fool with.

--

On Thursday, March 2, 2023 at 05:38:25 PM EST, JoeStrout ***@***.***> wrote: 

You can work around this by mounting the desired folder when you launch, using the -usr argument. See: https://miniscript.org/wiki/Command-line_arguments

But it certainly shouldn't crash. If you can get any details (error message, etc.), please attach them here!

**Comment by juh9870** [comment]
Why not use the Windows version of MiniMicro if you are on Windows?

**Comment by JoeStrout** [comment]
(Closed this issue just to keep the issues list neat, as it seems no action is required.)
