### ISSUE TITLE
fatbits not compliant with upcoming MM 1.2 parsing

### ISSUE THREAD

**Issue by sebnozzi** [JoeStrout/minimicro-sysdisk#8]
Small issue ... On line 1257:

```
Swatch.make = function(x, y, c=color.white, selected=false)
	noob = new Swatch
	noob.init x, y, c, selected
	return noob
end function
```

The argument `c=color.white` does not have a "literal" as default value.

This will cause a parsing error in MM 1.2.

Solution would be of course something like:

```
Swatch.make = function(x, y, c=null, selected=false)
        if c == null then c = color.white
	noob = new Swatch
	noob.init x, y, c, selected
	return noob
end function
```

**Comment by JoeStrout** [comment]
You're right!  This was never valid (even prior to MM 1.2), though we would have gotten away with it if we never actually made use of the default value.  And a simpler solution would be to just use `c="#FFFFFF"`.  But this is a great catch, thank you!
